name: mollie_pay
description: >
  Flutter helper to start a Mollie checkout, return to the app via deep link,
  and expose a simple success/pending/failed status for in-app payments.
version: 1.0.0

repository: https://github.com/goutam2597/mollie_pay.git
issue_tracker: https://github.com/goutam2597/mollie_pay/issues
topics:
  - payments
  - checkout
  - mollie

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.13.0
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  # declare assets here if needed
